### ISSUE TITLE
Translation to russian

### ISSUE THREAD

**Issue by Felix14-v2** [A5b84/dark-loading-screen#12]
I am attending GitHub recently, and I have not found another way to offer a translation. Anyway, here's the translation file:
[ru_ru.zip](https://github.com/A5b84/dark-loading-screen/files/5841649/ru_ru.zip)

I also suggested adding new settings in another issue, here is their translation into russian:

Изменять фон в указанный период времени:   [   Да   ]
Время начала: [21:00]
Время окончания: [6:00]

**Comment by A5b84** [comment]
I've added it to version [1.6.2](https://github.com/A5b84/dark-loading-screen/releases/tag/v1.6.2), thanks :)

(not on CurseForge yet because the site broke or something)
