### ISSUE TITLE
Bar Color is displayed incorrectly when OptiFine is installed

### ISSUE THREAD

**Issue by Serega007RU** [A5b84/dark-loading-screen#17]
I think everything is clear from the video

https://user-images.githubusercontent.com/64780091/124225587-624b6500-db10-11eb-9e39-d36be7cb5121.mp4

**Comment by A5b84** [comment]
Looks like that's caused by OptiFine, I may fix it (again) at some point but for the time being if you want to keep Optifine you can replace my mod with [this resource pack](https://www.curseforge.com/minecraft/texture-packs/dark-loading-screen) (shameless plug)

**Comment by A5b84** [comment]
Fixed in v1.6.11
