### ISSUE TITLE
Newest version of mod crashes on loading

### ISSUE THREAD

**Issue by windowslogic** [A5b84/dark-loading-screen#19]
Minecraft crashes while loading because of "Bad Variable Type". When removing Dark Loading Screen, the game loads fine.

**Comment by A5b84** [comment]
Send your logs and I'll look into it (see https://fabricmc.net/wiki/player:tutorials:logs_ml:windows, you can drag and drop your logs into GitHub directly instead of using a third party site)

**Comment by A5b84** [comment]
Closed because no response, if anyone can reproduce this feel free to reopen the issue

**Comment by A5b84** [comment]
Note: this is caused by optifine, see [this comment](https://www.curseforge.com/minecraft/mc-mods/dark-loading-screen?comment=51)

**Comment by A5b84** [comment]
Fixed in v1.6.11
