### ISSUE TITLE
Compat: Mojang logo renders 'transparent' with mod semitranslucency-fix

### ISSUE THREAD

**Issue by MeeniMc** [A5b84/dark-loading-screen#20]
### Summary

The Mojang log renders 'transparent' when the mod 'semitranslucency-fix' is also installed.

### Details

When the logo fades-in and out, the color is correct (default white), however, during the time period where the logo is static and the progress bar advances, the logo turns black and is barely visible on the dark gray background.

This is caused by a bad interaction with 'semitranslucency-fix'  https://modrinth.com/mod/semitranslucency (a mod that supports alpha-blending the background in menus and hud elements, e.g., the crafting table, see AquaHUD resource pack for example of use https://www.curseforge.com/minecraft/texture-packs/aquahud)

The most probable cause is that Dark-loading-screen encodes the colors as RGB only values (e.g., logo color is `#ffffff`); which is understood by semitranslucency as having a 0 alpha channel. Maybe a simple fix is to extend colors to contain an Alpha channel (e.g., `#ffffffff`), the first `ff` would have no use in vanilla minecraft, but would improve compatibility with this sort of mods.

**Comment by A5b84** [comment]
Fixed in v1.6.10
