### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Serega007RU** [A5b84/dark-loading-screen#21]
I get a crash if I run it with your mod, without this mod everything starts normally
[latest.log](https://github.com/A5b84/dark-loading-screen/files/7229248/latest.log)
[crash-2021-09-25_08.59.47-client.txt](https://github.com/A5b84/dark-loading-screen/files/7229249/crash-2021-09-25_08.59.47-client.txt)

There is no such problem in the older version 1.6.7

**Comment by A5b84** [comment]
Fixed in v1.6.11
