### ISSUE TITLE
Add BG_bg Support

### ISSUE THREAD

**Issue by natee22** [A5b84/dark-loading-screen#23]
Json Below to do so.

`
{
    "darkLoadingScreen.config.title": "Настройки на Dark Loading Screen",
    "darkLoadingScreen.config.entry.background": "Цвят на фона",
    "darkLoadingScreen.config.entry.bar": "Цвят на запълване на панела",
    "darkLoadingScreen.config.entry.barBackground": "Цвят на фона на панела",
    "darkLoadingScreen.config.entry.border": "Цвят на ръба на панела",
    "darkLoadingScreen.config.entry.logo": "Цвят на логото",
    "darkLoadingScreen.config.entry.fadeIn": "Продължителност на избледняване",
    "darkLoadingScreen.config.entry.fadeOut": "Продължителност на затъмняването",
    "darkLoadingScreen.config.entry.preview": "Визуализация"
}
`

**Comment by A5b84** [comment]
Merged, thanks!
