### ISSUE TITLE
Options Button Not Apearing

### ISSUE THREAD

**Issue by twizinho** [A5b84/dark-loading-screen#28]
i don't know if this is happening to just me, but i have this mod and Cloth Config installed and the Options button **[the one to personalize the Dark Loading Screen mod, not the main Minecraft options.]** simply doesn't appear, i even re-installed Cloth Config to see if some change is made, but still nothing.

![Sem título](https://user-images.githubusercontent.com/95052258/209223995-6862f9ad-bb85-4be5-af8e-2374cdd49266.png)

![Sem título](https://user-images.githubusercontent.com/95052258/209224131-f6f7766c-267a-4e02-a902-bd01801cbe87.png)

**Comment by A5b84** [comment]
Fixed in version 1.6.13
