### ISSUE TITLE
Background color gets added to logo color

### ISSUE THREAD

**Issue by Hnaguski** [A5b84/dark-loading-screen#5]
When setting a custom logo color it appears to add each r/g/b value of the background color to the logo color. For example if I set the background color to 112233 and the logo color to 001122 the color that is actually displayed on the logo is 113355. This also makes it impossible to have a black logo as setting the color to 000000 will just make it the same color as the background.
<details>
  <summary>Image Examples</summary>

The settings in modmenu
![settings](https://user-images.githubusercontent.com/29007712/89211370-b6ac3480-d58f-11ea-9e4b-233f885e03ae.png)

Background color
![bg](https://user-images.githubusercontent.com/29007712/89212178-0808f380-d591-11ea-91f5-7afa4a813d98.png)

Logo color
![logo](https://user-images.githubusercontent.com/29007712/89212161-00494f00-d591-11ea-84ab-9196b427335d.png)

Trying to make a black logo
![blacklogo](https://user-images.githubusercontent.com/29007712/89211969-a8aae380-d590-11ea-8149-5b735f20aef0.png)

But it's invisible
![invislogo](https://user-images.githubusercontent.com/29007712/89211989-b1031e80-d590-11ea-9612-915369b33908.png)

</details>

**Comment by A5b84** [comment]
Thanks for the report, I'll look into that
