### ISSUE TITLE
option to add loading bar background colour

### ISSUE THREAD

**Issue by Chrisblox** [A5b84/dark-loading-screen#8]
As the title says it would be nice to also be able to change the colour of the background in the loading bar area.

![mojang loading screen bar background](https://user-images.githubusercontent.com/35179334/91676105-a065aa00-eb36-11ea-9034-bb6cdf170835.png)

Great mod thanks!

**Comment by A5b84** [comment]
ye that should be doable

**Comment by A5b84** [comment]
Done, I'll release it later though there's a bug I want to fix first
